version: "3.9"
services:

  dynamodb-local:
    image: amazon/dynamodb-local:2.5.4
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath . -optimizeDbBeforeStartup
    ports:
      - "8000:8000"
    environment:
      AWS_ACCESS_KEY_ID: dummy0000dummy
      AWS_SECRET_ACCESS_KEY: dummy0000dummy
    volumes:
      - dynamodb:/home/dynamodblocal
    working_dir: /home/dynamodblocal

  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin:5.1.3
    environment:
      - DYNAMO_ENDPOINT=dynamodb-local:8000

    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local

networks:
  default:
    driver: bridge

volumes:
    dynamodb:
        driver: local
